# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://NTLresearch.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb  
github_username:  jekyll

permalink: /:categories/:title

links:
- title: Về chúng tôi
  url: /about
- title: Đầu tư giá trị
  url: /VI
- title: Toán tài chính
  url: /MF
- title: Lý thuyết portfolio
  url: /PM
- title: Programming
  url: /Programming
- title: Statistics
  url: /Stats
- title: Track Record
  url: /TR
- title: Misc
  url: /Misc


# Build settings
markdown: kramdown
