# Site settings
title: NTL RESEARCH
email: NTLresearchgroup@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Luôn có những rủi ro liên quan đến vấn đề đầu tư bao gồm cả việc mất toàn bộ vốn. Hiệu quả đầu tư trong quá khứ
  không đảm bảo cho kết quả trong tương lai. Nhà đầu tư nên xem xét cẩn thận mục tiêu đầu tư, ràng buộc, rủi ro và
  những chi phí liên quan.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://NTLresearch.github.io" # the base hostname & protocol for your site
twitter_username: D4xu0
github_username:  NTLresearchgroup

permalink: /:categories/:title
paginate_path: "/blog/page:num/"
paginate: 18

links:
- title: Về chúng tôi
  url: /about
- title: Đầu tư giá trị
  url: /VI
- title: Toán tài chính
  url: /ToanTaiChinh
- title: Lý thuyết portfolio
  url: /PM
- title: Programming
  url: /Programming
- title: Statistics
  url: /Stats
- title: Track Record
  url: /TR
- title: Misc
  url: /Misc
- title: portfolio
  url: /portfolio


# Build settings
markdown: kramdown
highlighter: rouge
google_analytics: UA-121799914-1
